language: ruby
env:
  - CXX=g++-4.8 CC=gcc-4.8
rvm:
  - 2.0
  - 2.1
  - 2.2
  - 2.3.1
before_install:
  - gem install bundler -v 1.12.0
  - update-alternatives --auto g++
  - update-alternatives --auto gcc
cache: bundler
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
