language: ruby
rvm:
  - 2.2
  - 2.3
  - 2.4
  - 2.5
matrix:
  include:
    - rvm: 2.5.1
      os: osx
      osx_image: xcode9.4
    - rvm: 2.4.0
      os: osx
      osx_image: xcode8.3
    - rvm: 2.4.0
      os: osx
      osx_image: xcode7.3
dist: trusty
sudo: true
before_install:
  - gem update --system
  - gem install bundler -v 1.12.0
cache: bundler
