language: ruby
rvm:
  - 2.0
  - 2.1
  - 2.2
  - 2.3.1
before_install: gem install bundler -v 1.12.0
cache: bundler
sudo: false
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
